# themes from https://github.com/alacritty/alacritty-theme

[general]
import = [
    "~/.config/alacritty/themes/themes/gruvbox_dark.toml"
]

[font]
size = 12

[font.normal]
family = "FiraCode Nerd Font Mono"

[window]
decorations = "none"

[window.padding]
x = 10
y = 0
